version: '3'

env:
  GITHUB_USER: mcpradeep

dotenv:
  - .env
  - .ignore/.env

includes:
  alpaca:
    taskfile: ./alpaca
    dir: ./alpaca
  badger:
    taskfile: ./badger
    dir: ./badger
  camel:
    taskfile: ./camel
    dir: ./camel

tasks:
  bootstrap: 
    desc: Bootstrap Flux on a new cluster
    # cmd: flux bootstrap github
    #   --owner={{.GITHUB_USER}}
    #   --repository=clusters-flux
    #   --branch=main
    #   --path=./alpaca
    #   --personal
    cmds:
      - task: install
      # - task: bootstrap-git-secret
      - task: camel:apply
  
  bootstrap-git-secret:
    cmd: >
      flux create secret git github-token --username $GITHUB_USER --password $GITHUB_TOKEN
      --url=https://github.com/$GITHUB_USER/clusters-flux.git

  install: flux install

  suspend: flux suspend kustomization --all && flux suspend helmrelease --all
  resume: flux resume kustomization --all && flux resume helmrelease --all
  
  uninstall:
    desc: Uninstall Flux on a cluster
    summary: |
      Uninstall Flux on a cluster.
      Note: Does not remove components installed via Flux
    cmd: flux uninstall
