apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../cluster-components-flux
- ../../cluster-components-flux/optional/charlie.yaml

labels:
  - pairs:
      gwcp.guidewire.com/dept: '20'
      atmos-cluster: alpaca

patches:
  - target:
      name: alpha
      kind: HelmRelease
    patch: |
      - op: replace
        path: /spec/values/replicaCount
        value: 3
      - op: replace
        path: /metadata/labels/gwcp.guidewire.com~1dept
        value: 22
      - op: add
        path: /spec/postRenderers/0/kustomize/patches/-
        value:
          patch: |-
            - op: replace
              path: /metadata/labels/gwcp.guidewire.com~1dept
              value: '23'
          target:
            name: .*
            kind: .*
      - op: add
        path: /spec/postRenderers/0/kustomize/patches/-
        value:
          patch: |-
            - op: replace
              path: /spec/template/metadata/labels/gwcp.guidewire.com~1dept
              value: '24'
          target:
            name: .*
            kind: Deployment
  - target:
      name: bravo
      kind: HelmRelease
    patch: |
      - op: replace
        path: /spec/values/replicaCount
        value: 2
  - target:
      name: charlie
      kind: HelmRelease
    patch: |
      apiVersion: builtin
      kind: LabelTransformer
      metadata:
        name: add-managed-by-label
      labels:
        gwcp.guidewire.com/app-code: charlie
        gwcp.guidewire.com/tenant-code: 1234